Am add locale field to editions template
guardian/facia-tool pull request #1250
Opened 2020-09-04 12:59 UTC by aoifemcl15

## What's changed?

In preparation to remove the US edition, we thought that the app shouldn't be dependant on the existence of any particular edition. 
This PR adds a new `locale` field which the editions app can use to decide which default edition to select for a new user based on their selected locale.
**Note** The locale field is only relevant for Regional Editions. 

I have deployed this branch to CODE to check that the field comes through as expected https://fronts.code.dev-gutools.co.uk/editions-api/editions

## Implementation notes

## Checklist

### General
- [ ] 🤖 Relevant tests added
- [ ] ✅ CI checks / tests run locally
- [ ] 🔍 Checked on CODE

### Client
- [ ] 🚫 No obvious console errors on the client (i.e. React dev mode errors)
- [ ] 🎛️ No regressions with existing user interactions (i.e. all existing buttons, inputs etc. work)
- [ ] 📷 Screenshots / GIFs of relevant UI changes included

2020-09-07 09:40 UTC, aug24 requested changes

2020-09-07 09:40 UTC, aug24 commented on app/model/editions/templates/TheDummyEdition.scala
> +  override val locale = Some("dm_DM")
I'm concerned this might prevent us viewing the Dummy Edition on devices.  May I suggest en_GB instead?

2020-09-07 09:40 UTC, aug24 commented on app/model/editions/templates/TrainingEdition.scala
> +  override val locale = Some("tr_TR")
I'm concerned this might prevent us viewing the Training Edition on devices.  May I suggest en_GB instead?

2020-09-07 09:40 UTC, aug24 commented on test/fixtures/TestEdition.scala
> +  override val locale: Option[String] = Some("tt_TT")
I doubt if we will ever want the Test Edition, but this isn't a valid Locale.  I'd suggest using some valid one.

Do the tests correctly check this value?

2020-09-07 09:45 UTC, jennygrahamjones commented
I don't have a lot of context for this, but if it's something that's only relevant to editions that extend `RegionalEdition`, is it possible to make this field part of that trait rather than the base `EditionDefinition`?

2020-09-15 09:58 UTC, aoifemcl15 commented
> I don't have a lot of context for this, but if it's something that's only relevant to editions that extend `RegionalEdition`, is it possible to make this field part of that trait rather than the base `EditionDefinition`?

Sounds like a good idea, however, my scala is very limited so I'm not sure how I would go about adding the `locale` to the `RegionalEdition` since it is currently defined as an abstract class instead of a trait, any guidance would be appreciated 🙂

2020-09-15 10:20 UTC, jennygrahamjones commented
> > I don't have a lot of context for this, but if it's something that's only relevant to editions that extend `RegionalEdition`, is it possible to make this field part of that trait rather than the base `EditionDefinition`?
> 
> Sounds like a good idea, however, my scala is very limited so I'm not sure how I would go about adding the `locale` to the `RegionalEdition` since it is currently defined as an abstract class instead of a trait, any guidance would be appreciated 🙂

Reading @aug24's comments, it looks ike we would need these value on the `InternalEdition` implementations too, so probably not worth worrying about at the moment 👍

2020-09-17 14:59 UTC, aug24 approved these changes

2020-09-18 08:38 UTC, merged